[package]
name = "inx-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
inx = { version = "0.1.0", path = "../inx" }
once_cell = "1.17.0"
owo-colors = "3.5.0"
